### ISSUE TITLE
Issue with in-app purchase system

### ISSUE THREAD

**Issue by Achnazoor** [paavu/floatoo#1]
Hi. 
I tried to use the in-app purchase system to buy you a coffee in order to unlock the app, but I keep getting an error saying "Transaction was declined". This happens after I validate the payment and authentcate using my fingerprint. It looks like a payment system pop-up rather than an app-specific one.

**Comment by paavu** [comment]
Hi Achnazoor,

First of all, I truly appreciate that you liked my app and like to
contribute

further, I apologize for the inconvenience,
Google has blocked our in-app sale due to some Policy change in Brazil, and
we have already submitted the required documentation and completed the
process requirements.
It may take a couple of days to restore my Google app purchases

for your update, we have been working on another big update that includes
an additional sidebar launch mode
*assistive touch:* Instead of a swipe from sideBar, if the user wants a
touch launch mode.

Please stay with Floatoo
Again appreciate your support

Best Regards
Aneesh Chopra

Founder | CTO
http://paavu.com

**Comment by paavu** [comment]
> Hi. 
> I tried to use the in-app purchase system to buy you a coffee in order to unlock the app, but I keep getting an error saying "Transaction was declined". This happens after I validate the payment and authentcate using my fingerprint. It looks like a payment system pop-up rather than an app-specific one.

Hi,
In-app purchase has been restored in Floatoo
Today. Let me know if you try to buy me a coffee and still face similar issue.

Thank you
